### PR TITLE
some additions

### PR DESCRIPTION
**Pull request by meriadec**
- add readme
- update a bit codemirror config
- put editor data in editor reducer (when typing in editor, etc)
- ability to save as gist (very minimal)
- retrieve gist via url (e.g: `/gists/asnetuhsonthusaonthso`) and populate gist reducer
- limit to 5 tabs
- use redux devtools extension if available
- update nodemon config to reload only when server folder change (and route file)
- update route configuration to have ability to prefetch data from component (via `load` static, see `Home` component => fetch gist)
- add notifications system ( = Alerter )
- update a bit tab style to prevent fail click on close

### CODE REVIEW

**Comment by meriadec** [comment]
- lint :D

**Comment by meriadec** [comment]
- some refactoring/clean
- api middleware
- display gist file list and ability to click on them to open tab

**Comment by meriadec** [comment]
- add modal
- working remove file from gist (with confirm modal)

**Comment by lohek** [comment]
Wow nice, thanks 👌 for you it's ok for merge ?

**Comment by meriadec** [comment]
yep, even there is still a lot of work to do, but we need discuss about it. so yep, you can merge that, and we'll see together the future devs

**Comment by lohek** [comment]
Ok perfect, it's more easy for me to continue work on that with merge 💃

**Pull request merged**
